### PR TITLE
LOG-2090: Enable `drain_on_shutdown` to see if it stops H13 errors.

### PR DESCRIPTION
**Pull request by mjkillough**
Enable `drain_on_shutdown` to see if this stops the H13 errors we see on
Heroku. Linux establishes connections and maintains a queue of sockets
to return when the application calls `Socket.accept`. The Heroku router
seems to expect all of these to be serviced before the application shuts down -
they aren't transferred to another worker if they are not.

I think this my final theory, after which 🤷‍♂️ .

However, I really would like to fix these errors as:
 - Right now we're completely ignoring HTTP 503 errors from Data Sink and Routemaster. This is a huge broken window and we're bound to miss something major.
 - The Heroku router puts a lot of effort into ensuring this doesn't happen and it's a real shame that we aren't benefitting from this.

### CODE REVIEW

**Comment by humzashah** [comment]
Question: what will draining on shutdown do? Ensure that the request queue for the dyno is served before shutting down? (meanwhile blocking new requests to that dyno?)

**Comment by mjkillough** [comment]
During shutdown, it repeatedly calls `.accept()` on the socket, until there are no more connections to accept. It will then ensure each of those requests are served before finally allowing the server to shutdown.

This should drain the kernel's queue of established connections. Heroku changes the status of the dyno before sending the `SIGTERM` signal, which should stop new incoming connections, so the queue shouldn't continue to grow. (This is not well documented, so there is a chance that I am wrong. In this case the graceful shutdown should timeout and the Puma processes will be uncleanly killed. The impact of this would be a few errors, similar to the H13 errors we see today).

[This diagram](https://github.com/puma/puma/blob/master/docs/architecture.md) is useful to understand the various queues that are involved here. However, I think it is wrong, because I think that the connections in the Socket's backlog are 'accepted' as far as Heroku is concerned, [as this is how Linux's `listen()` works.](http://man7.org/linux/man-pages/man2/listen.2.html#NOTES)

**Comment by humzashah** [comment]
Thanks for the explanation, @mjkillough - really appreciated. :)

I mainly wanted to ensure that we wouldn't be in a state where we're waiting for the queue to empty so we can restart but the queue never empties. Our guess is that it won't, which is fine.

**Comment by mjkillough** [comment]
> I mainly wanted to ensure that we wouldn't be in a state where we're waiting for the queue to empty so we can restart but the queue never empties. Our guess is that it won't, which is fine.

Yeah. All [Heroku docs](https://devcenter.heroku.com/articles/error-codes#r12-exit-timeout) that I can find suggest that if our guess is incorrect (and the dyno continues to process requests indefinitely), it'll get a `SIGKILL` and will exit with an R12 error. Even if this happens, I don't think it's actually much worse than the H13 error we're getting today... In either case, let's hope it doesn't happen!

**Comment by mjkillough** [comment]
I'm closing this for now. See the discussion in the ticket - it seems Heroku router continues to give us requests even during shutdown. I can't see how we can shutdown gracefully in this case. :(

**Pull request closed without merging**
